Sprint 1
wibimipi/middle.messenger.praktikum.yandex pull request #1
Opened 2022-12-12 15:46 UTC by wibimipi

2022-12-12 16:13 UTC, podlovchenko requested changes
Привет, все здорово, хорошая работа, но нет ссылки на нетлифай в ридми, нужно добавить и почистить проект от пустых файлов

2022-12-12 16:13 UTC, podlovchenko commented on .gitignore
> +/.github
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-12-12 16:13 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-12-12 16:13 UTC, podlovchenko commented on server.js
> +const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-12-12 16:13 UTC, podlovchenko commented on src/pages/profile/profile.scss
> +  & > a {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-12-13 09:15 UTC, podlovchenko requested changes

2022-12-13 09:15 UTC, podlovchenko commented on README.md
> +![Netlify](https://teal-pie-6426aa.netlify.app/)
По ссылке сейчас page not found

2022-12-13 12:08 UTC, temss-front commented on README.md
> +![Netlify](https://teal-pie-6426aa.netlify.app/)
Настроил автодеплой, должно работать

2022-12-13 14:28 UTC, podlovchenko commented
Супер, спасибо за правки, работу принимаю

2023-02-28 19:09 UTC, merged